INSERT INTO PERSON (ID, NAME, HAS_CAR, GENDER, AGE) VALUES
(1, 'Ivan', FALSE, 'M', 12),
(2, 'Lenka', FALSE, 'F', 40),
(3, 'Mark', TRUE, 'M', 30),
(4, 'Bob', FALSE, 'M', 38);

INSERT INTO SIBLING(ID1, ID2) VALUES (3, 4);

INSERT INTO SPOUSE(ID1, ID2) VALUES (4, 2);

INSERT INTO PARENT(CHILD_ID, PARENT_ID) VALUES (1, 2), (1, 4);