CREATE TABLE PERSON (
    ID INT  PRIMARY KEY,
    NAME VARCHAR(255),
    HAS_CAR BOOLEAN,
    GENDER CHAR(1)
);       

INSERT INTO PERSON(ID, NAME, HAS_CAR, GENDER) VALUES
(1, 'Ivan', FALSE, 'M'),
(2, 'Lenka', FALSE, 'F'),
(3, 'Mark', TRUE, 'M'),
(4, 'Martin', FALSE, 'M');

CREATE TABLE SIBLING(
    ID1 INT,
    ID2 INT
);

INSERT INTO SIBLING(ID1, ID2) VALUES (3, 4);

CREATE TABLE SPOUSE(
    ID1 INT,
    ID2 INT
);

INSERT INTO SPOUSE(ID1, ID2) VALUES (4, 2);

CREATE TABLE PARENT(
    CHILD_ID INT,
    PARENT_ID INT
);

INSERT INTO PARENT(CHILD_ID, PARENT_ID) VALUES (1, 2), (1, 4);